feat: DEV-2885: Add new dm columns
heartexlabs/dm2 pull request #83
Opened 2022-07-19 19:47 UTC by Travis1282

2022-07-19 19:59 UTC, juliosgarbi requested changes

2022-07-19 19:59 UTC, juliosgarbi commented on src/stores/DataStores/tasks.js
> +  console.log(columns);
You forgot this console.log, it should be removed

2022-07-19 20:28 UTC, bmartel submitted a review, later dismissed
The new additions should be behind a feature flag.

2022-07-20 15:02 UTC, juliosgarbi approved these changes
LGTM

2022-07-20 15:33 UTC, merged