fix: DEV-3110: Load any missing user data for comments
heartexlabs/dm2 pull request #95
Opened 2022-08-05 22:06 UTC by bmartel

2022-08-08 13:32 UTC, hlomzik requested changes

2022-08-08 13:32 UTC, hlomzik commented on src/sdk/comments-sdk.js
> +      .reduce((ids, id) => !id || ids.includes(id) ? ids : [id, ...ids], []);
that's just to make them uniq? maybe use `uniq` or `[...new Set(<..>)]`?

2022-08-08 14:41 UTC, bmartel commented on src/sdk/comments-sdk.js
> +      const { id, email, username, first_name, last_name, avatar, initials } = await this.dm.apiCall("user", {
I was originally concerned about what the api docs was suggesting is returned in these object representations. It had mentioned that the hashed passwords were being returned when I checked the local openapi docs, but I would rather just return the value.

2022-08-09 14:16 UTC, hlomzik approved these changes

2022-08-10 11:37 UTC, merged